{*
 generated by Prestaweb.ru from pwdeveloper module
*}
	<footer id="footer">
		<div class="footer_inner no_fill footer-light ext_view">
			<div class="bottom_wrapper">
				<div class="wrapper_inner">
					<div class="row bottom-middle">
						<div class="col-md-7">
							<div class="row">
								<div class="col-md-4 col-sm-4">
									<div class="bottom-menu">
										<div class="items">
											<div class="item-link">
												<div class="item">
													<div class="title">
														{l s='Categories'}
													</div>
												</div>
											</div>
											<div class="wrap">
                      {foreach from=$table_category item=category}
												<div class="item-link">
													<div class="item">
														<div class="title">
															<a href="{$link->getCategoryLink({$category.id_category})}">{l s={$category.name}}</a>
														</div>
													</div>
												</div>
                        {/foreach}
											</div>
										</div>
									</div>
								</div>
								<div class="col-md-4 col-sm-4">
									<div class="bottom-menu">
										<div class="items">
											<div class="item-link">
												<div class="item">
													<div class="title">
														{l s='Information'}
													</div>
												</div>
											</div>
											<div class="wrap">
												<div class="item-link">
													<div class="item">
														<div class="title">
															<a href="{$link->getPageLink('prices-drop')}">{l s='Prices drop'}</a>
														</div>
													</div>
												</div>
												<div class="item-link">
													<div class="item">
														<div class="title">
															<a href="{$link->getPageLink('new-products')}">{l s='New products'}</a>
														</div>
													</div>
												</div>
												<div class="item-link">
													<div class="item">
														<div class="title">
															<a href="{$link->getPageLink('best-sales')}">{l s='Best sales'}</a>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="col-md-4 col-sm-4">
									<div class="bottom-menu">
										<div class="items">
											<div class="item-link">
												<div class="item">
													<div class="title">
														<a href="#">Свободные страницы</a>
													</div>
												</div>
											</div>
											<div class="wrap">
												<div class="item-link">
													<div class="item">
														<div class="title">
															<a href="#">Page 1</a>
														</div>
													</div>
												</div>
												<div class="item-link">
													<div class="item">
														<div class="title">
															<a href="#">Page 2</a>
														</div>
													</div>
												</div>
												<div class="item-link">
													<div class="item">
														<div class="title">
															<a href="#">Page 3</a>
														</div>
													</div>
												</div>
												<div class="item-link">
													<div class="item">
														<div class="title">
															<a href="#">Page 4</a>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-5">
							<div class="row">
								<div class="col-lg-6 col-md-12 col-sm-6">
									<div class="social-block rounded_block">
										<div class="social-icons">
											<div class="small_title">
												Оставайтесь на связи
											</div><!-- noindex -->
											<ul>
												<li class="vk">
													<a href="1" rel="nofollow" target="_blank" title="Вконтакте">Вконтакте</a>
												</li>
												<li class="facebook">
													<a href="2" rel="nofollow" target="_blank" title="Facebook">Facebook</a>
												</li>
												<li class="twitter">
													<a href="3" rel="nofollow" target="_blank" title="Twitter">Twitter</a>
												</li>
												<li class="instagram">
													<a href="4" rel="nofollow" target="_blank" title="Instagram">Instagram</a>
												</li>
												<li class="ytb">
													<a href="5" rel="nofollow" target="_blank" title="YouTube">YouTube</a>
												</li>
												<li class="odn">
													<a href="6" rel="nofollow" target="_blank" title="Одноклассники">Одноклассники</a>
												</li>
												<li class="gplus">
													<a href="7" rel="nofollow" target="_blank" title="Google Plus">Google Plus</a>
												</li>
												<li class="mail">
													<a href="8" rel="nofollow" target="_blank" title="Mail.ru">Google Plus</a>
												</li>
											</ul><!-- /noindex -->
										</div>
									</div>
								</div>
								<div class="col-lg-6 col-md-12 col-sm-4 col-sm-offset-2">
									<div class="info contacts_block_footer">
										<span class="white_middle_text">Наши контакты</span> <!--'start_frame_cache_header-allphones-block2'-->
										<div class="phone blocks">
											<!-- noindex -->
											<div class="phone with_dropdown">
												<i class="svg svg-phone"></i> <a href="tel:+70000000010" rel="nofollow">+7 (000) 000-00-10</a>
												<div class="dropdown">
													<div class="wrap">
														<div class="more_phone">
															<a href="tel:+70000000011" rel="nofollow">+7 (000) 000-00-11</a>
														</div>
														<div class="more_phone">
															<a href="tel:+70000000012" rel="nofollow">+7 (000) 000-00-12</a>
														</div>
													</div>
												</div>
											</div><!-- /noindex -->
										</div><!--'end_frame_cache_header-allphones-block2'--><!--'start_frame_cache_email-block1'--><!--'end_frame_cache_email-block1'--><!--'start_frame_cache_address-block2'-->
										<div class="address blocks">
											{$shop_addres_footer}
										</div><!--'end_frame_cache_address-block2'-->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>